// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwFx9Qyemy-zZEVKf1mkszzR3kG-kzYE',
    appId: '1:713700814221:web:1a9c13c9f98934856121c4',
    messagingSenderId: '713700814221',
    projectId: 'db-life-hub',
    authDomain: 'db-life-hub.firebaseapp.com',
    storageBucket: 'db-life-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSL0c7Wjisc1-YmpNAJsiKjofsRsRzTbE',
    appId: '1:713700814221:android:13051d51d5c2915d6121c4',
    messagingSenderId: '713700814221',
    projectId: 'db-life-hub',
    storageBucket: 'db-life-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIE2l8zSgwATY93w8jAY7MLapBhvKOGs',
    appId: '1:713700814221:ios:51fcff73da3335376121c4',
    messagingSenderId: '713700814221',
    projectId: 'db-life-hub',
    storageBucket: 'db-life-hub.firebasestorage.app',
    iosBundleId: 'com.example.lifeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIE2l8zSgwATY93w8jAY7MLapBhvKOGs',
    appId: '1:713700814221:ios:51fcff73da3335376121c4',
    messagingSenderId: '713700814221',
    projectId: 'db-life-hub',
    storageBucket: 'db-life-hub.firebasestorage.app',
    iosBundleId: 'com.example.lifeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwFx9Qyemy-zZEVKf1mkszzR3kG-kzYE',
    appId: '1:713700814221:web:3b176766df3804626121c4',
    messagingSenderId: '713700814221',
    projectId: 'db-life-hub',
    authDomain: 'db-life-hub.firebaseapp.com',
    storageBucket: 'db-life-hub.firebasestorage.app',
  );
}
